### ISSUE TITLE
灵敏度设置 效果不是很理想。

### ISSUE THREAD

**Issue by knItalian** [liantian-cn/logitech-pubg#11]
没和之前的对比过， 现在这个版本 我30和默认50  还是有比较明显的差距， 调低后枪口还是会往上抬 感觉转换的不是很完美，还可以继续优化吗

**Comment by liantian-cn** [comment]
Fix！

研究了下UE引擎，这个鼠标灵敏度是指数关系而不是线性关系。
至于pubg，应该是这么计算的。  ` 实际灵敏度 = 0.002 * math.pow(10, 面板灵敏度/ 50);`

代码已更新
