### ISSUE TITLE
开火问题

### ISSUE THREAD

**Issue by lpj8213756** [liantian-cn/logitech-pubg#12]
开火fire key按键需要和游戏内设置一致，在游戏内取消鼠标左键的绑定。
开火键默认为pause。
那么能修改成鼠标上的按键吗，我是小白，无意间发现这个网站和你的作品。

**Comment by liantian-cn** [comment]
理论上可以的，可以替换 
PressAndReleaseKey为PressAndReleaseMouseButton，
ReleaseKey为ReleaseMouseButton
PressKey为PressMouseButton
按键用数字代替


但反过来，也可以用LGS将某个鼠标按键绑定为pause，这样更方便。
