### ISSUE TITLE
Keyboard key

### ISSUE THREAD

**Issue by mcgbg** [liantian-cn/logitech-pubg#15]
Hi, 
**local set_off_key =**  can we assign a keyboard key? 
Thanks.

**Comment by liantian-cn** [comment]
@mcgbg 

Yes, but only the special buttons of the Logitech game keyboard. (G key and M key)

You can open C:\Program Files\Logitech Gaming Software\Resources\Doc\G-seriesLuaAPI.pdf, and then modify this statement.

`if (event == "MOUSE_BUTTON_PRESSED" and arg == set_off_key) then`
