### ISSUE TITLE
使用的时候不能自动只能单点？

### ISSUE THREAD

**Issue by papiJohn** [liantian-cn/logitech-pubg#16]
我的情况是无论是自动模式还是单点模式都只能单点了

**Comment by liantian-cn** [comment]
试试以管理员身份运行LGS
文件坐标："C:\Program Files\Logitech Gaming Software\LCore.exe"
可以在这个程序的属性>兼容性，勾选以“管理员身份运行此程序”

**Comment by papiJohn** [comment]
可以了，不过自动模式压枪幅度会过大，是正常的？

**Comment by liantian-cn** [comment]
@papiJohn 是的...这只是业余制作，并没有太大精力调整参数。
枪械建议都使用单发模式，只感觉m16比较好用。m4不如不用（切换到none）

**Comment by papiJohn** [comment]
@liantian-cn 现在又好了！非常感谢，自己再调灵敏度就很好用了！！！
