### ISSUE TITLE
Firing

### ISSUE THREAD

**Issue by TheZeek** [liantian-cn/logitech-pubg#17]
when firing can do you have to press the pause button or can you still use left click?

**Comment by TheZeek** [comment]
Thank you. I went through the code and it seems to be one of the best recoil scripts out for PUBG :)

**Comment by papiJohn** [comment]
Right, if it doesn't work, try to open the logitech software with administrator privileges. Or if it doesn't work well, just adjust the targeting sensitivity to an appropriate value.
