### ISSUE TITLE
Invalid after yesterday's update (10/27/2017)

### ISSUE THREAD

**Issue by ANPULI** [liantian-cn/logitech-pubg#18]
No Recoil became invalid after yesterday's update. However, quick clicking (连点) provided by another script of mine still works. I can give you the script if you want.

**Comment by besteric** [comment]
i try this script yesterday night (23:00 GMT8) still works

**Comment by ANPULI** [comment]
Okay I will try it again later. Hope it still works

**Comment by liantian-cn** [comment]
still work here.

two possible causes and  solutions.

1. run LGS as administrator 

UAC will isolate user32.dll‘s function between users and administrators. both [keybd_event](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646304(v=vs.85).aspx) and [SendInput ](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646310(v=vs.85).aspx)function are in user32.dll. so if you run pubg as administrator , you also need to run LGS as administrator.

well.
You may not notice that pubg in the admin, may be pubg is child process of steam.exe , and steam is child process of steam update , steam update must run as admin. 

2. set "Lock profile while game is running"

By default ， LGS will only run profile when game's window is "active",  use [GetActiveWindow  ](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646292(v=vs.85).aspx), but in windows 10 , input and notification will often become active window, maybe bug maybe not.

**Comment by liantian-cn** [comment]
update readme 
https://github.com/liantian-cn/logitech-pubg/commit/d14e06860d0b8ed13e0ae73d447af95c78b0cb87#diff-04c6e90faac2675aa89e2176d2eec7d8
