### ISSUE TITLE
If I use G102 ,I Can use it

### ISSUE THREAD

**Issue by aomchey** [liantian-cn/logitech-pubg#19]
![image](https://user-images.githubusercontent.com/32266753/32133956-c208952a-bc0c-11e7-94e1-9a300619aaf4.png)

If I can use it, Where should I fix it?

**Comment by liantian-cn** [comment]
G102 does not have "PROGRAMMABLE BUTTONS"  feature .

At least G302, or more advanced models

![G302](http://www.logitech.com/assets/53095/5/logitech-gaming-software-images.jpg)
