### ISSUE TITLE
食用说明有一事不明

### ISSUE THREAD

**Issue by yiios** [liantian-cn/logitech-pubg#2]
如果把射击按键绑定为键盘按键左，并取消鼠标左键在游戏内的绑定。
这句话怎么理解,什么是键盘按键左,而且如果取消鼠标左键(也就是射击键)的绑定的话,不就开不出抢了么.
ps:我是从 NGA 摸过来的.

**Comment by yiios** [comment]
OK 我看了https://github.com/liantian-cn/logitech-pubg/issues/1明白了 键盘按键左是指的方向键左吧

**Comment by Johny1989** [comment]
把游戏内射击键改成方向键左键 就能正常用了 或者编辑脚本把Left替换成其他键也可以

**Comment by yiios** [comment]
宏孩儿还是不好滴 不过我还是默默 fork 了 哈哈
