### ISSUE TITLE
AK的后坐力还是过大。

### ISSUE THREAD

**Issue by Biseny** [liantian-cn/logitech-pubg#21]
AK的后坐力还是过大。

**Comment by liantian-cn** [comment]
=.= 
没办法，AK的垂直和水平方向的随机性都很大。压枪宏并不能发挥什么作用。

0后座那种是修改pak文件，压枪宏做不到。

**Comment by Biseny** [comment]
https://www.mpgh.net/forum/showthread.php?t=1309932

**Comment by Biseny** [comment]
看下这个。也许能用
