### ISSUE TITLE
recoil too fast

### ISSUE THREAD

**Issue by CabalyZ** [liantian-cn/logitech-pubg#26]
I did all the procedures including the settings in the game I use 700 dpi in the mouse, and 29, 29, 30 in the sensibilities in the game.

When I'm firing the gun it goes down a lot.

the weapon decays a lot

can you help me?

**Comment by liantian-cn** [comment]
change sensitivity setting in script

line 35-40

**Comment by CabalyZ** [comment]
--- Sensitivity in Game
--- default is 35.0

local target_sensitivity = 35
local scope_sensitivity = 35
local scope4x_sensitivity = 35

Is good?

**Comment by liantian-cn** [comment]
You should set same with the game menu

**Comment by CabalyZ** [comment]
Ok, thanks

**Comment by CabalyZ** [comment]
--- Sensitivity in Game
--- default is 63.0

*Script

local target_sensitivity = 63
local scope_sensitivity = 63
local scope4x_sensitivity = 63

*PUBG

local target_sensitivity = 36
local scope_sensitivity = 36
local scope4x_sensitivity = 36

this configuration is perfect
