### ISSUE TITLE
关于分配按键功能

### ISSUE THREAD

**Issue by shionv** [liantian-cn/logitech-pubg#28]
首先感谢大佬分享
问题是 关于

> 分配一个按键使用ump9，这样按键同时也适合全配件的m416和scar-l.
分配一个按键使用m16a1, m16a1搭配红点瞄准镜或全息瞄准镜，不需要其他配件，就可以发挥威力。
分配一个按键使用akm，akm的模式同样适用于sks和mini 14.

此段不甚明了，是指在LGS的按键分配界面给功能侧键分配上如代码内绑定好的数字例如8 5 7 吗？这样的话岂不是应该与游戏内的数字快捷键冲突？还是有什么别的所指？谢谢赐教

**Comment by liantian-cn** [comment]
按键是指鼠标的功能键，编号在下方日志
