### ISSUE TITLE
发现个问题，游戏灵敏度会影响脚本的使用啊

### ISSUE THREAD

**Issue by knItalian** [liantian-cn/logitech-pubg#3]
最开始我以为弹道会很集中 但实际枪口还是会向上抬 ，不过效果也很明显的 减小了一大半的后坐力  还是很给力的 
---------
自己瞎捣鼓了一下，游戏里瞄准 开镜的灵敏度 都会影响脚本的使用，DPI好像没影响 ， 请问作者自己测试的时候 用的是多少灵敏度啊

**Comment by liantian-cn** [comment]
灵敏度：50

我倒是没注意，因为一直没改过。

**Comment by knItalian** [comment]
@liantian-cn 
嗯  我之前是30， 调成50后弹道完全没问题了，  这样的话我要调低DPI 不然50对我来说太高了不适应 
如果有办法转换最好 灵敏度和recoil_table之间

**Comment by liantian-cn** [comment]
@knItalian 嗯..

**Comment by liantian-cn** [comment]
@knItalian 
新增了设置
```
local target_sensitivity = 50.0
local scope_sensitivity = 50.0
local scope4x_sensitivity = 50.0
```
对应游戏的腰射灵敏度，1倍灵敏度和4倍灵敏度.
![](https://github.com/liantian-cn/logitech-pubg/raw/master/20171015014208.png)
