### ISSUE TITLE
打开武器速度后，speed仍然是30

### ISSUE THREAD

**Issue by spellforce** [liantian-cn/logitech-pubg#30]
需要把 local weapon_speed = recoil_table[_weapon]["speed"] 中的local 定义去掉才行

但是用了武器速度后，压枪及其不准

**Comment by liantian-cn** [comment]
thx

**Comment by spellforce** [comment]
压枪数据全是自己测试出来的吗，感觉好费时间，怎么依靠官网提供的后坐力数据一起搞

**Comment by liantian-cn** [comment]
@spellforce 并不打算继续搞了。
实际上，当游戏时间>100小时时，这东西就没用了。蹲下、趴下，不同配件都是不同的后坐力。
在这之前，虽然不准，但也够用了。
