### ISSUE TITLE
武器延迟问题

### ISSUE THREAD

**Issue by spellforce** [liantian-cn/logitech-pubg#31]
感觉罗技的sleep延迟不准，调成武器速度后，理论上应该打多少发子弹，数组走到哪，可实际不是这样，游戏中子弹打出的速度不一致，只有50ms以内感觉延迟准一点。请问一下是我的原因还是罗技的原因呢？

**Comment by liantian-cn** [comment]
游戏的原因，延迟的原因...

这个测试过了，所以默认是30ms...
