### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by barryjim** [liantian-cn/logitech-pubg#32]
你好，你的宏写的很好，但是在运行过程中，我发现了点问题，就是有时候宏是运行的，自带的软件测试也可以，但是就是进游戏里 无法运行。 枪在自动上模式中，按住鼠标也只能射出一发子弹。

**Comment by liantian-cn** [comment]
管理员身份执行LGS
参见 [常见问题--无法自动射击](https://github.com/liantian-cn/logitech-pubg#常见问题--无法自动射击)
