### ISSUE TITLE
MOUSE_BUTTON_PRESSED 事件

### ISSUE THREAD

**Issue by barryjim** [liantian-cn/logitech-pubg#33]
你好，前面那个问题，我再补充一下，在游戏里，我鼠标上 绑定的大跳，吃药都是能运行的，但是脚本上的连发，和后座力没有，按住鼠标也就发了 一个PAUSE. 我查了 罗技的api，里面说 ：鼠标按键被按下时
注意：鼠标左键 (1) 默认将不会对此事件进行回应。您可以使用 
‘EnablePrimaryMouseButtonEvents
’ 方法将其覆盖。 会不会和这个有关？              
      如果是这个原因，那应该是一次都不会成功，不会返回状态。奇怪的就是有时行有时不行，昨天不行，今天就行了

**Comment by liantian-cn** [comment]
管理员身份执行LGS
