### ISSUE TITLE
关于修改游戏内灵敏度

### ISSUE THREAD

**Issue by siriume** [liantian-cn/logitech-pubg#35]
游戏内灵敏度更改是否可以直接乘以倍数
weapon_recoil = recoil_table[_weapon][_mode][step] *  50/29
或者
weapon_recoil = recoil_table[_weapon][_mode][step] *  1.72

**Comment by liantian-cn** [comment]
参考代码第104行
```
math.pow(10, unconvertedSens / 50)
```

游戏内的灵敏度，和实际的dpi，并不是倍数关系。而是(10^(n/50))/10关系，是非线性的。
