### ISSUE TITLE
可以增加一个快速瞄准功能吗?

### ISSUE THREAD

**Issue by planetesaoko** [liantian-cn/logitech-pubg#36]
按住右键机械瞄准 松开右键释放的  我有一个ahk脚本 但我不会移植到罗技

*RButton:: ; Fast Aiming
if ADS = 1
{ ; If enabled, clicks once and clicks again when button is released.
  SendInput {RButton}
  SendInput {RButton Down}
  KeyWait, RButton
  SendInput {RButton Up}
} else { ; If not, just keeps holding until button is released.
  SendInput {RButton Down}
  KeyWait, RButton
  SendInput {RButton Up}
}
Return

**Comment by liantian-cn** [comment]
这个，改配置文件就可以啊。

go to
C:\Users\YOURACCOUNTNAME\AppData\Local\TslGame\Saved\Config\WindowsNoEditor
open with notepad:
GameUserSettings.ini
Ctrl-F and search for:
InputModeADS=Toggle
and change it to
InputModeADS=Hold

来自reddit：https://www.reddit.com/r/PUBATTLEGROUNDS/comments/7cwxe0/pubg_started_banning_people_using_ini_file_tweaks/

**Comment by planetesaoko** [comment]
我的朋友修改.ini获得了游戏开发者永久封禁,所以我不想修改这些文件,这样修改没有开关不能自由切换,如果你有时间的话,可以考虑加入这个功能,谢谢 非常实用!
