### ISSUE TITLE
我有个问题

### ISSUE THREAD

**Issue by yswcdmm** [liantian-cn/logitech-pubg#37]
随机时间的定义 AK 的射速为 100 有时候随机出来射速 小于100了 表示这一枪是空的 这样的是否导致了 反冲的不准？

**Comment by liantian-cn** [comment]
游戏有延迟补偿。
同时每个人延迟也不一样 。
再同时延迟补偿怎么计算的不知道。
游戏的tick甚至不如射速。

太多变量了，所以没法说。

不过大概率，子弹是打出去了。

不过不用太纠结于这个射击间隔，较小的间隔(默认30ms) ，可以使用更大的随机变量范围的同时保持手感。

随机变量范围越大，越不容易被规则检查检测出来。
不过，现在并不存在这种规则检测....所以功能做出来也只是做出来。
