### ISSUE TITLE
有在关注测试服数据吗?

### ISSUE THREAD

**Issue by CoderMaurice** [liantian-cn/logitech-pubg#38]
各枪弹道差异比较大

**Comment by yswcdmm** [comment]
自己去调试啊 修改反冲数据

**Comment by liantian-cn** [comment]
木.....

作者只是业余的，并没那么大精力。

**Comment by zyqd1** [comment]
测试服并没有什么大改动  数据通用  不过AK可以自己重新调整一下。我感觉作者已经做的够多了，剩下的自己解决吧。

**Comment by CoderMaurice** [comment]
@liantian-cn 能否告知一下现在版本的后座力表格数据是在哪里获得的 国外的论坛吗?
我关注一下新版本的数据 如果有这个能力的话  可以帮忙维护这个项目

**Comment by zyqd1** [comment]
好像这个数据比较难找。 我自己调试的方式是比较原始的进游戏射击，看弹道调整脚本数据。耗费精力非常多，我想作者可能没有这个时间吧。

**Comment by CoderMaurice** [comment]
@zyqd1 我记得作者好像说过他的表格是网上找的 我现在也在国外的论坛找 不过没有找到后座表格

**Comment by yswcdmm** [comment]
看弹道的偏移 进行修改就好

**Comment by liantian-cn** [comment]
@CoderMaurice 
mpgh : mpgh.net/forum/forumdisplay.php?f=913
uc : unknowncheats.me/forum/playerunknown-s-battlegrounds/
基本上这两个找到..
部分是ahk改过来的。

**Comment by MikuKissedMe** [comment]
@liantian-cn 
首先感谢大佬的宏！
但是我在脚本里没有找到有关大跳/big jump的词和设置，怀疑是我瞎了。

**Comment by yswcdmm** [comment]
@MikuKissedMe  大跳是自己设置的 C按下 空格按下 延迟500毫秒 c 空格 释放就行了。。。 自己去按键那里录制。。。。

**Comment by MikuKissedMe** [comment]
@yswcdmm 
我还以为是脚本自带一个！ 感谢！

**Comment by liantian-cn** [comment]
https://github.com/liantian-cn/logitech-pubg/commit/9aa55c9b375729bbd84532985d4de18e84a5e829

更新了 recoil_table...

基础瞄具的已更新

众所周知的原因，四倍镜拿了就快递了，所以四倍数据没有维护。

**Comment by liantian-cn** [comment]
#47 
这里有测试的效果截图
总结下：

M16的水平方向随机后座力变大了，仅次于AKM，这把枪削弱了。

AKM的前5-7发子弹的水平后座力减少，后续后座力依然爆炸，枪算是增强了。

M4和SCARL的垂直方向后座力更小了，满配后请禁用压枪宏使用...
