### ISSUE TITLE
English Guide

### ISSUE THREAD

**Issue by DirkH96** [liantian-cn/logitech-pubg#39]
Can someone that understands both the Chinese as the English language make a guide for the English users? 
I don't think any non-Chinese users can make any sense what so ever of this guide.

**Comment by CoderMaurice** [comment]
@DirkH96 see this
https://www.mpgh.net/forum/showthread.php?t=1322543

**Comment by siming85** [comment]
i just created a pull request

there's obviously a lot of things i could further smooth out, but eh, did enough to make it a bit more legible.

**Comment by liantian-cn** [comment]
@siming85 Thank U ！！！！
