### ISSUE TITLE
Please help me out

### ISSUE THREAD

**Issue by kris8899** [liantian-cn/logitech-pubg#40]
1. Can I change the mode switch key? other than Capslock?

2. Do I have to match in-game sensitivity and sensitivity in the script?

3. What is weapon speed mode?

4. What is obfs mode?

5. Does interval ratio mean interval between each bullet?

6. What is random speed?

7. Any update when PUBG v1.0 comes out?

Thanks a lot

**Comment by liantian-cn** [comment]
Can I change the mode switch key? other than Capslock?

YES,  can also use numlock or scrolllock .

Do I have to match in-game sensitivity and sensitivity in the script?

YES  .  the value in the script should equal to the game menu

What is weapon speed mode?

This is a test mode , Mouse click interval will be longer then default....but useless now
 
What is obfs mode?
Does interval ratio mean interval between each bullet?
What is random speed?

in obfs mode:  shooting interval, not a fixed 30ms, will be dynamic within a certain range. increasing the difficulty of detection.
interval ratio &  random speed   > just variables in the formula.
shooting interval = weapon_speed * interval_ratio * ( 1 + random_seed * ( 0 ~ 1))

Any update when PUBG v1.0 comes out?

No..  I think it is not necessary.
this project is just an example, everyone can modify according to their own preferences no recoil table.  in release version , There is more randomness on recoil .
