### ISSUE TITLE
鼠标键不够用了

### ISSUE THREAD

**Issue by charliezzo** [liantian-cn/logitech-pubg#41]
鼠标的键不够用了。怎么把几个枪合在一起。

**Comment by charliezzo** [comment]
发现把这个配置导进去。然后管理员运行，设置了开火是pause还是不能开火。所有键都不能开火。

**Comment by alechy** [comment]
指定一个按键,为Gun_key,点一下切换一下...

function TransGun()
    IsOnClick = false
    Gun = Gun + 1
    if Gun == 1 then
        current_weapon = "ump9"
    end
    if Gun == 2 then
        current_weapon = "m16a4"
    end
    if Gun == 3 then
        current_weapon = "akm"
    end
    if Gun == 4 then
        current_weapon = "scarl"
    end
    if Gun == 5 then
        current_weapon = "m416"
    end
    if Gun == 6 then
        current_weapon = "none"
    end
    GunType = 1
end

if (event == "MOUSE_BUTTON_PRESSED" and arg == Gun_Key) then
	TransGun()
end
