### ISSUE TITLE
Possible Use of Logitech Keyboard Keys ?

### ISSUE THREAD

**Issue by FreakerBln** [liantian-cn/logitech-pubg#43]
Hello Sir,

is it Possible to assign the Weapon Keys to "my" Logitech G15 Keyboard cause like the Name says on this i have 15 G Keys ..

I know that it gives G Pressend etc.. but all my "test" are not Working.

Could/Would you Help me ??

Thanks in Advance

**Comment by liantian-cn** [comment]
i am not sure,  I do not have Logitech Keyboard....

you can write a simple script , only 3 lines , then type any G key on keyboard ,  if have anything put into the log window,  G-key in keyboard will work.

function OnEvent(event, arg)
    OutputLogMessage("event = %s, arg = %d\n", event, arg)
end
