### ISSUE TITLE
can you fix another logitech lua of pubg

### ISSUE THREAD

**Issue by charliezzo** [liantian-cn/logitech-pubg#44]
昨天看到一个售价599元的罗技宏，但是他的模式很多，alt shift caplock numlock等等，鼠标是压了，但是不自动开枪，还分点射连射啥的，你要不要看一下。

**Comment by liantian-cn** [comment]
=.=没那个必要啦....

压枪宏不是无后坐力挂，能做到的有限，不要强求...
