### ISSUE TITLE
recoil table need update in version 1.0 server

### ISSUE THREAD

**Issue by besteric** [liantian-cn/logitech-pubg#45]
I think recoil tables are outdated for most weapons on 1.0 server...

**Comment by ouzerdo** [comment]
yes, please update

**Comment by Lebedev73** [comment]
pls pls pls)) update) ty

**Comment by liantian-cn** [comment]
#38

**Comment by liantian-cn** [comment]
updated
https://github.com/liantian-cn/logitech-pubg/commit/9aa55c9b375729bbd84532985d4de18e84a5e829
