### ISSUE TITLE
游戏内灵敏度要调到多少

### ISSUE THREAD

**Issue by TRAAACER** [liantian-cn/logitech-pubg#48]
看脚本里面写的是50
--- Sensitivity in Game
--- default is 50.0
local target_sensitivity = 50
local scope_sensitivity = 50
local scope4x_sensitivity = 50
可是使用说明里面有张图里面是29左右
所以应该使用哪种呢

**Comment by liantian-cn** [comment]
图只是个例子

和游戏里一样就是了
