### ISSUE TITLE
问下大大测试 脚本 用的鼠标dpi是多少的？

### ISSUE THREAD

**Issue by pzxton** [liantian-cn/logitech-pubg#5]

**Comment by kingwangboss** [comment]
你的能自动开火？

**Comment by pzxton** [comment]
我还没用，回家试试，但是dpi不一样肯定还要调参数的吧

**Comment by kingwangboss** [comment]
我试过了，不能自动开火

**Comment by liantian-cn** [comment]
@pzxton 默认是50，可以参考[issues/5](https://github.com/liantian-cn/logitech-pubg/issues/5)进行修改。

**Comment by liantian-cn** [comment]
@kingwangboss 需要在游戏内取消fire的鼠标左键绑定，并绑定为"pause"，这个也可以修改。

**Comment by kingwangboss** [comment]
@liantian-cn 我已经替换了pause，但是还是单发。

**Comment by liantian-cn** [comment]
@kingwangboss 是不是使用了加速器？

**Comment by kingwangboss** [comment]
@liantian-cn 是的

**Comment by kingwangboss** [comment]
@liantian-cn 单次点击，可以触发滚动，可是不能连发

**Comment by liantian-cn** [comment]
@kingwangboss 
试试以管理员身份运行LGS
文件坐标："C:\Program Files\Logitech Gaming Software\LCore.exe"
可以在这个程序的属性>兼容性，勾选以“管理员身份运行此程序”

**Comment by liantian-cn** [comment]
@kingwangboss move https://github.com/liantian-cn/logitech-pubg/issues/4

**Comment by kingwangboss** [comment]
@liantian-cn 可以了，鼠标灵敏度 是改成dpi的值吧

**Comment by kingwangboss** [comment]
@liantian-cn 我的dpi灵敏度是4级

**Comment by liantian-cn** [comment]
@kingwangboss 不对....鼠标灵敏度=游戏内的鼠标灵敏度设置，默认是50

罗技鼠标的dpi设置不影响宏的位移。这个过程罗技已经处理好了。
