### ISSUE TITLE
关于四倍镜和八倍镜的倍数问题

### ISSUE THREAD

**Issue by mektpoy** [liantian-cn/logitech-pubg#51]
请问开四倍镜和八倍镜的时候后坐力是什么样的关系？和放大倍数一样吗？ 即四倍镜的时候x4，八倍镜的时候x7.25这样？ 但我看这段lua代码并不是这么写的而是做了一个比例比较奇怪的表格，而且556的枪四倍镜的表格比较一致，我不太理解这是什么原因。

**Comment by liantian-cn** [comment]
并不是倍数的关系.....每把枪，每个倍数，有独立的后座力。

其实并不打算维护四倍了，之所以有，跟为什么有这个项目有关系。

“当年网吧看见过一个人用罗技鼠标宏，还说花了500RMB，我看了眼代码，觉得.....自己写一个好了”

那个500元的宏里有四倍，所以也就有了四倍。

实际上，四倍镜的情况随机性更大，不适合连发，两枪打一个人很难。不如手动单点。
