### ISSUE TITLE
It's possible to add horizontal position of mouse in recoil table?

### ISSUE THREAD

**Issue by podolkerod** [liantian-cn/logitech-pubg#52]
Hi Lianli, thanks for your amazing work.

Is there any chance to add horizontal position of mouse in current recoil table?

**Comment by mektpoy** [comment]
I think it's impossible.
SCAR-L with angled / vertical / none
![tim 20180103200217](https://user-images.githubusercontent.com/31686206/34519847-09656acc-f0c1-11e7-982b-7998f2ca7285.png)
M416
![tim 20180103200211](https://user-images.githubusercontent.com/31686206/34519857-10badf00-f0c1-11e7-8155-6ddc2c4c3c5e.png)
SKS
![tim 20180103200203](https://user-images.githubusercontent.com/31686206/34519863-15be613e-f0c1-11e7-868e-9c42f71157f1.png)

We can see the recoil's randomness on horizontal position.

**Comment by liantian-cn** [comment]
@podolkerod 
lgs can do it .
but pubg not CS:GO.
