### ISSUE TITLE
提供一个四倍镜M16的后坐力

### ISSUE THREAD

**Issue by mektpoy** [liantian-cn/logitech-pubg#53]
quadruple={86.7,86.7,86.7,86.7,86.7,86.7,86.7,150,150,150,150,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120}

效果如图，总体来说之前的表格十发子弹之后后坐力偏差三分之一。。
![tim 20180103193223](https://user-images.githubusercontent.com/31686206/34518964-d5af6f9c-f0bc-11e7-90ff-57bfef0b30e8.png)

**Comment by liantian-cn** [comment]
Thank U~

**Comment by bmq-code** [comment]
@mektpoy 你好，我想问一下这个数据怎么测出来的我想自己测。谢谢
