### ISSUE TITLE
你好,请问解包后的文件名  类似a.uasset .通过虚幻引擎打不开.和UE的版本有关系吗?我是4.18.2

### ISSUE THREAD

**Issue by FengLeee** [liantian-cn/logitech-pubg#54]
如果有关系,哪个版本能够查看呢?  谢谢

**Comment by alechy** [comment]
4.18.2新了,现在1.0版本的是基于4.16.3的.

不过,你下载了4.16.3 ,发现还是打不开,求作者来个打开方法.

**Comment by FengLeee** [comment]
4.16.3我也打不开...

**Comment by liantian-cn** [comment]
https://www.unknowncheats.me/forum/playerunknown-s-battlegrounds/250116-edit-uasset-file-extension-ue4.html

**Comment by alechy** [comment]
大大,
看看我的步骤:

1. 用PakUnpacker.exe 解开PAK文件.比如 TslGame-WindowsNoEditor_objects.pak 得到了一个 TslGame 的文件夹.

2.通过Steam\steamapps\common\PUBG\Engine\Build\Build.version 得知当前UE4 的版本是 4.16.3,UE4下载4.16.3

3.打开UE4的4.16.3,创建空白工程,然后关闭.

4.复制 TslGame文件夹到Content目录和StarterContent一致.

5.重新打开UE4 4.16.3

6.点击相应的文件. 然后,显示加载资源失败...

求大大解惑.谢谢.

**Comment by liantian-cn** [comment]
@alechy 
如果被`编译`过的uasset是没办法导入的。
不知道编译这个词准确不，我不是做游戏开发的啦。
这是想修改无后么？1.0版本无后自己修改和用大众版本，安全上是一样的。

**Comment by alechy** [comment]
@liantian-cn  问题在这里,大大,你的这个参数是如何通过uasset获得的?
是不是要搞一下umodel的源码看看?
https://github.com/gildor2/UModel

**Comment by liantian-cn** [comment]
另外还有一个歪道，但是100%安全。

1. 删除TslGame_BE.exe
2. 将TslGame.exe重命名为TslGame_BE.exe

启动游戏，这就是一个未启动BE的pubg，当然，连接不了任何服务器。

然后你就可以使用任何内存挂的方法研究游戏的数据了。

有C++的基础，可以看。

https://github.com/G-E-N-E-S-I-S/TslGame_MULTI_HACK

https://github.com/jussihi/PUBG-map-hack

https://github.com/pubgsdk/PUBG-SDK
