### ISSUE TITLE
Im using G203 Gaming Mouse

### ISSUE THREAD

**Issue by giaphongdau** [liantian-cn/logitech-pubg#55]
Im using G203 Gaming Mouse, and I don't know how to setup, I pressed the forward button, it seem to work but I cant stop it when I want. also, how the key binding work? I have no idea

**Comment by alechy** [comment]
G203 have only 3 keys,you can bind 2 guns,and one key bind to stop scripts...

**Comment by giaphongdau** [comment]
https://goo.gl/oSS2Sg
I only see 2 key
BTW, the key bind is on the mouse? not on the keyboard? can you tell me the number of the mice? I don't know what number should I put for the forward button and back button.. please help me

**Comment by alechy** [comment]
emm... 
2 keys..
Buy G502 / G402 / G300s /...

**Comment by liantian-cn** [comment]
https://www.logitechg.com/en-us/product/g203-prodigy-gaming-mouse#featuresAnchor

sorry, G203 does not have features : "programmable key"
