### ISSUE TITLE
Mouse script. Change effect by use attachments?

### ISSUE THREAD

**Issue by yukine-prizzy** [liantian-cn/logitech-pubg#57]
hey, im not good in english but i need help.
what if i but some attachments on my M416 or UMP or scar or M16. will the effect of it change? will it end? if is just work without attachments ? 
what if i use scope? like (4xscope) do i understand right i must click on capslock when i wanna use the weapon with 4xscope? 

and do i must let "fire" on "pause" ? because i dont like it that is always on auto! i wanna switch between singel and Auto.

**Comment by liantian-cn** [comment]
if u have full attachments with m4 , turn off script~

**Comment by yukine-prizzy** [comment]
Ok thx. But then better i dont use attachments. Because with script its better the full attachments. Thanks
