### ISSUE TITLE
 请问一下 那手榴弹如何˙扔出?

### ISSUE THREAD

**Issue by dc7361** [liantian-cn/logitech-pubg#6]
开火键已改成Pause 手榴弹一按滑鼠左键就扔出去 不能停留在手上

**Comment by liantian-cn** [comment]
问的好...让我考虑考虑

**Comment by liantian-cn** [comment]
- [ ] 丢雷

**Comment by liantian-cn** [comment]
Todo:
- [ ] 丢雷

**Comment by pzxton** [comment]
设置一个取消所有压枪的键。按一下 。扔手雷。 或者设置一个键盘按键 比如alt 按住 暂时取消压枪 扔手雷

**Comment by liantian-cn** [comment]
@pzxton 谢谢建议

**Comment by pzxton** [comment]
@liantian-cn 大神客气了。我也就是提供思路 多谢你分享源码才是

**Comment by liantian-cn** [comment]
@dc7361 现在修改了关闭压枪的按键规则。在“关闭”状态下，没有连点效果了，恢复游戏本来的效果。同时按住左shift同样的效果。
@pzxton 建议的alt键实测，因为和观察视野冲突，所以没采用。同时，左shift是用狙击枪时屏息的按键，正好屏息连狙手动压强效果更好。谢谢建议。

**Comment by dc7361** [comment]
謝謝 大神!
