### ISSUE TITLE
偶尔开不了枪，请教蓝天大佬

### ISSUE THREAD

**Issue by harveyxiacn** [liantian-cn/logitech-pubg#60]
谢谢蓝天大佬这个超厉害的宏。让萌新的我能压住枪来刚了。只是偶尔会出现开不了枪（鼠标左键没反应，但是按pause是有的），需要关闭重开游戏才行。请教一下是不是我哪里没设置好，谢谢

**Comment by liantian-cn** [comment]
lgs里右键游戏，设置，有个在游戏运行时锁定配置的选项。

**Comment by liantian-cn** [comment]
默认情况，lgs只对active的窗口生效，不过在win10里面，游戏是否处于active窗口跟性能没关系，同时游戏往往也不是那个唯一的active窗口。

**Comment by harveyxiacn** [comment]
原来是这样，我看到介绍里面的了，只是没明白这段的意思。现在明白了，原来自己撞上了哈哈哈。谢谢蓝天大佬
