### ISSUE TITLE
想請問遊戲中的幾個問題

### ISSUE THREAD

**Issue by yogo1234** [liantian-cn/logitech-pubg#61]
想請問遊戲中的解析度有無限制要設定多少
可以在自己額外增加暫停或取消鍵嗎? 想多一個Tab鍵也是暫停功能鍵
Caps Lock鍵在文件中更改別按鍵後，整個宏會變得無作用?
謝謝

**Comment by alechy** [comment]
1.应该无限制
2.可以加的
3.这个参照下罗技自带的说明文档,可以改其它键,还能用的是numlock 和 scrolllock ...

**Comment by liantian-cn** [comment]
这个代码，只是一个范例，不是一个万能的商品，个性化的需求，自己改下代码的啦~

**Comment by yogo1234** [comment]
只剩如何增加一個 local set_off_key 鍵的拉~
直接增加上去就好? 還是?
我現在local set_off_key = 6(滑鼠)，想再多增加一個local set_off_key = "TAB" ，現在直接多加一行變沒有效果....

**Comment by liantian-cn** [comment]
@yogo1234 

tab的话，不可以的....逻辑不支持

如果想用numlock (或 scrolllock)，可以修改为

修改
if ((current_weapon == "none") or IsModifierPressed(ignore_key)) then
为
if ((current_weapon == "none") or IsKeyLockOn(”numlock“)) then


numlock可修改为

"scrolllock" Scroll Lock
"capslock" Caps Lock
"numlock" Number Lock
