### ISSUE TITLE
my g600 not work

### ISSUE THREAD

**Issue by dacara** [liantian-cn/logitech-pubg#64]
Hello liantian.
Im testing the script with logitech g600 but it dont work for me.
I followed the tutorial and I changed the buttons
"local ump9_key = 12
local akm_key = nil
local m16a4_key = 16
local m416_key = nil
local scarl_key = nil
local uzi_key = nil"
but nothing happens when i click. I try with/without admin execute on steam/lgs.
could u help me? thx

**Comment by liantian-cn** [comment]
set "Lock profile while game is running"
By default ， LGS will only run profile when game's window is "active", use GetActiveWindow , but in windows 10 , input and notification will often become active window, maybe bug maybe not.
