### ISSUE TITLE
request 

### ISSUE THREAD

**Issue by thestranger00** [liantian-cn/logitech-pubg#66]
can you make a "no recoil" only script please? without rapid fire or any other macro .. only recoil or just guide me how to do it? It'll be much appreciated :) thanks alot

**Comment by liantian-cn** [comment]
Try [Easy Mode](https://github.com/liantian-cn/logitech-pubg/blob/master/easy_mode.lua)

**Comment by thestranger00** [comment]
do you mind telling me how to use it :o
