### ISSUE TITLE
经过测试发现后面几发子弹压得有点过

### ISSUE THREAD

**Issue by kingwangboss** [liantian-cn/logitech-pubg#7]

**Comment by whitemarble** [comment]
我刚也试过了，作者在recoil_value那个函数里忘记乘前面人工加的随机数延迟因子了，你把那个coefficient添加到recoil_value参数里，里面的return数值直接乘上这个因子就好了。目前只有站立姿态的垂直后坐力表，所以只有站着射是OK的

另外记得调节灵敏度参数！

**Comment by kingwangboss** [comment]
@whitemarble ok 了，我没看懂参数，已经添加好了
