### ISSUE TITLE
the m416 recoil is a bit too low 

### ISSUE THREAD

**Issue by P1nkB4nny** [liantian-cn/logitech-pubg#75]
hey,
the m416 recoil is a bit too low where do i edit the script to make the vertical recoil more agrassive?

**Comment by mcalis** [comment]
Hi, you need to change recoil table for that gun. (Quadruple is for 4X scope)
All that numbers(comma , is separator) in single row represent a recoil by bullet. (30 bullets MAG), if you want more recoil counter in mid section of a MAG, you increase numbers somewhere in the middle of the row, if you now what I mean.
I have been using this for several weeks now, i would say macro is good in this order, from best to worst AK ->M16 -> M4 -> SCAR . I don't even use it when i have scar, its bad. I did't try any edits of the recoil table by myself yet.

**Comment by P1nkB4nny** [comment]
that was very helpful thx. 
btw i agree, the ak is on point
