### ISSUE TITLE
去哪里获取最新的后坐力数据表？外加一些改进

### ISSUE THREAD

**Issue by whitemarble** [liantian-cn/logitech-pubg#8]
Hi，我测试了一下
1. 你这个脚本有一个比较严重的问题，最终的后坐力数据计算错了！
如果直接按照官方的射击间隔数据，可能是由于按键延迟的问题没法做到每次都能成功射击导致100%不准。你加了个随机数的因子加大了射击间隔就挺好的了，但是你忘记考虑间隔延长后后坐力表的后坐力也要适当减弱，因为延迟的时间准心会有一定的自动修正。我简单的就把那个随机时间间隔因子放到计算后坐力的那个函数里了，直接让后坐力乘那个因子，最后测试结果挺好的了。
另外你里面那个_duration参数暂时没用，这个是游戏官方有数据的么？

2.后座力数据表去哪里找的？你以后会一直更新么？

3.我自己用scrolllock按键做了脚本开关，会比较方便，这样可以省出一颗鼠标按键来切换武器而不是切换成没有武器的后坐力。

4.目前的后坐力数据是机遇每把枪站立姿态的，可否今后再加入蹲着姿态的？正好可以用最后一颗numberlock按键来切换。

P.S. 目前正在考虑入个罗技G系列键盘，这样可以响应键盘事件，这个挂就有更多功能按键可用了，哈哈哈

**Comment by liantian-cn** [comment]
1.  如果固定射击间隔，确实比较容易套用后座力数据，但同时也容易被“规则检测”，随机射击间隔，会导致"后座力恢复"的时间有长有短，所以确实不如固定间隔的准确。

2. shoot_duration的作用，是鼠标按下的瞬间归零并开始计时的。

3. 后座力表是在mpgh \ elitepvpers 等论坛看帖子，将一些ahk/lhm脚本内的后座力抓来的，因为autohotkey/macroengine还是比较容易算第三方的。数值方面，我确实没精力自己测试收集，如果看到更新，会更新。

4. 蹲姿这个没注意，如果发现有会加入的，谢谢建议。

5. 开源的目的，一个是希望不要为了简单的东西花很多钱，还有一个目的就是抛砖引玉，希望大家可以拿来按需修改。（我在网吧加过别人250元买的脚本，代码粗糙，逻辑难懂=.=。）

**Comment by jiffxiao** [comment]
"我简单的就把那个随机时间间隔因子放到计算后坐力的那个函数里了，直接让后坐力乘那个因子，最后测试结果挺好的了。" 如何做？请赐教，感激。

**Comment by liantian-cn** [comment]
@jiffxiao whitemarble fork并新建了一个分支。 https://github.com/whitemarble/logitech-pubg/tree/wwh

**Comment by jiffxiao** [comment]
感谢~~
